### ISSUE TITLE
CloudFormation deployment fails (eu-west-1)

### ISSUE THREAD

**Issue by noobtron** [aws-samples/aws-serverless-security-workshop#51]

**Comment by rkustner** [comment]
I had the same issue and I see your PR hasn't been merged yet.

In my case I changed the template to use aurora serverless

```
  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    DependsOn: AuroraSubnetGroup
    DeletionPolicy: Delete
    Properties:
      MasterUsername: admin
      MasterUserPassword: !Ref DbPassword
      Engine: aurora-mysql
      EngineMode: serverless
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 2
        MinCapacity: 1
        SecondsUntilAutoPause: 3000
      DBSubnetGroupName: !Ref AuroraSubnetGroup
      VpcSecurityGroupIds:
        - !Ref AuroraSecurityGroup 
```
